# Generated by Django 5.2.17 on 2026-09-24 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(default='STUDIO NAME', max_length=120)),
                ('monogram', models.CharField(default='TW', help_text='Short mark shown in the header, e.g. two or three characters.', max_length=6)),
                ('role_line', models.CharField(default='TATTOO ARTIST / VISUAL ARTIST', max_length=160)),
                ('statement', models.TextField(blank=True, default='INK IS ONLY THE MEDIUM.', help_text="The artist's statement. Rendered as an editorial headline.")),
                ('biography', models.TextField(blank=True, help_text='Long-form biography. Blank lines become paragraphs.')),
                ('location_city', models.CharField(blank=True, max_length=80)),
                ('location_country', models.CharField(blank=True, max_length=80)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_booking_open', models.BooleanField(default=True, help_text='Second booking switch; both this and SiteSettings must be on.')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset')),
                ('user', models.OneToOneField(blank=True, help_text='Optional login link for the artist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'artist profile',
                'verbose_name_plural': 'artist profile',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(help_text='e.g. "10+", "1200+", "08"', max_length=20)),
                ('label', models.CharField(help_text='e.g. "YEARS", "TATTOOS"', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='artists.artistprofile')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['artist', 'order'], name='artists_sta_artist__574d49_idx')],
                'constraints': [models.UniqueConstraint(fields=('artist', 'order'), name='uniq_statistic_order')],
            },
        ),
    ]
