# Generated by Django 5.2.17 on 2026-09-24 06:22

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(max_length=255, upload_to=apps.core.models.media_upload_path)),
                ('kind', models.CharField(choices=[('original', 'Original'), ('derivative', 'Derivative'), ('dither', 'Dither'), ('lqip', 'Low-quality placeholder')], db_index=True, default='original', max_length=20)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('alt_text', models.CharField(blank=True, help_text='Describe the image for screen readers and search engines.', max_length=200)),
            ],
            options={
                'verbose_name': 'media asset',
                'verbose_name_plural': 'media assets',
                'indexes': [models.Index(fields=['kind', 'created_at'], name='core_mediaa_kind_fc2667_idx')],
                'constraints': [models.UniqueConstraint(fields=('sha256', 'kind'), name='uniq_asset_sha_kind')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='TattoWeb', max_length=120)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('hero_kicker', models.CharField(blank=True, default='TATTOO ARTIST / VISUAL ARTIST', help_text='Small mono line above the hero headline.', max_length=120)),
                ('hero_title', models.CharField(blank=True, default='ART THAT MOVES WITH YOU', help_text='The oversized headline. Line breaks are respected.', max_length=200)),
                ('default_meta_description', models.CharField(blank=True, max_length=320)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('studio_address', models.TextField(blank=True)),
                ('map_embed_url', models.URLField(blank=True)),
                ('booking_open', models.BooleanField(default=True, help_text='Master switch for the booking form.')),
                ('announcement', models.TextField(blank=True, help_text='Optional studio notice shown site-wide.')),
                ('hero_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset')),
                ('og_default_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('telegram', 'Telegram'), ('email', 'Email'), ('behance', 'Behance'), ('x', 'X / Twitter'), ('website', 'Website')], max_length=40)),
                ('label', models.CharField(help_text='Display text, e.g. @artist', max_length=80)),
                ('url', models.URLField(blank=True)),
                ('handle', models.CharField(blank=True, max_length=80)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'label'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='core_social_is_acti_ca13d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=70)),
                ('kind', models.CharField(choices=[('tattoo', 'Tattoo'), ('artwork', 'Artwork'), ('product', 'Product'), ('client', 'Client')], db_index=True, default='tattoo', max_length=20)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'kind'), name='uniq_tag_slug_kind')],
            },
        ),
    ]
