# Generated by Django 5.2.17 on 2026-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='dither_threshold',
            field=models.PositiveSmallIntegerField(default=118, help_text='Halftone cutoff (0-255). Lower = denser dots, keeps fine lines. Higher = sparser, protects dark artwork from crushing. Default 118.'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='dither_width',
            field=models.PositiveSmallIntegerField(default=1600, help_text='Working width for dither plate generation.'),
        ),
    ]
