# Generated by Django 5.2.17 on 2026-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaasset_dither_threshold_mediaasset_dither_width'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediaasset',
            name='uniq_asset_sha_kind',
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='variant_key',
            field=models.CharField(blank=True, db_index=True, help_text="Distinguishes variants of the same source image: '' for the original, the width for a derivative, 'dither' / 'lqip' for those plates.", max_length=40),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, help_text='Content hash of the ORIGINAL file. Shared by all variants of one image.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('sha256', 'kind', 'variant_key'), name='uniq_asset_sha_kind_variant'),
        ),
    ]
