# Generated by Django 5.2.17 on 2026-09-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset')),
            ],
            options={
                'verbose_name_plural': 'artwork categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('medium', models.CharField(blank=True, help_text='e.g. "Ink on paper".', max_length=120)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. "70 x 100 cm".', max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('commission', 'Commission'), ('private', 'Private collection')], db_index=True, default='available', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('edition_info', models.CharField(blank=True, help_text='e.g. "Ed. 2/25".', max_length=120)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='artworks', to='core.tag')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artworks', to='artworks.artworkcategory')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artwork_images', to='core.mediaasset')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['status', 'is_featured', '-year'], name='artworks_ar_status_d02381_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category', 'status'], name='artworks_ar_categor_d3fdbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(condition=models.Q(('price__isnull', True), ('price__gte', 0), _connector='OR'), name='artwork_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='artworkimage',
            constraint=models.UniqueConstraint(fields=('artwork', 'order'), name='uniq_artworkimage_order'),
        ),
        migrations.AddConstraint(
            model_name='artworkimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('artwork',), name='uniq_artwork_primary_image'),
        ),
    ]
