# Generated by Django 5.2.17 on 2026-09-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_placeholder',
            field=models.BooleanField(db_index=True, default=False, help_text='Demonstration content. Displayed with a visible notice on the site.'),
        ),
    ]
