# Generated by Django 5.2.17 on 2026-09-24 06:22

import apps.booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'availability',
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('weekday', 'start_time'), name='uniq_availability_slot'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='availability_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, help_text='Optional inclusive range end.', null=True)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('all_day', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='booking_blo_date_b7564b_idx'), models.Index(fields=['date', 'end_date'], name='booking_blo_date_02997b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('date')), _connector='OR'), name='blockeddate_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, default=apps.booking.models.generate_reference, max_length=12, unique=True)),
                ('placement', models.CharField(blank=True, max_length=80)),
                ('approx_size', models.CharField(blank=True, max_length=40)),
                ('is_color', models.CharField(choices=[('color', 'Colour'), ('black_grey', 'Black & grey'), ('undecided', 'Undecided')], default='undecided', max_length=10)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('potential', 'Potential client'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('preferred_date', models.DateField(blank=True, db_index=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('contact_consent', models.BooleanField(default=False)),
                ('source', models.CharField(default='web', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='clients.client')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tattoos.tattoostyle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('done', 'Done'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('calendar_event_id', models.CharField(blank=True, help_text='Reserved for a future Google Calendar sync. Unused today.', max_length=200)),
                ('internal_notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='booking.booking')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_references', to='core.mediaasset')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='booking.booking')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='booking_boo_status_75aeac_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['preferred_date'], name='booking_boo_preferr_23cfe8_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['client'], name='booking_boo_client__4f1e3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('budget_max__isnull', True), ('budget_min__isnull', True), ('budget_max__gte', models.F('budget_min')), _connector='OR'), name='booking_budget_range_valid'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start_at'], name='booking_app_start_a_b10326_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'start_at'], name='booking_app_status_447b5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='appointment_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='bookingreference',
            index=models.Index(fields=['booking'], name='booking_boo_booking_168301_idx'),
        ),
    ]
