# Generated by Django 5.2.17 on 2026-09-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        ('core', '0001_initial'),
        ('tattoos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('aspect', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape'), ('square', 'Square')], default='portrait', max_length=10)),
                ('span', models.PositiveSmallIntegerField(default=1, help_text='Grid span for asymmetry.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('artwork_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='artworks.artworkimage')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_images', to='core.mediaasset')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerycollection')),
                ('tattoo_image', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tattoos.tattooimage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['collection', 'order'], name='gallery_gal_collect_01b21d_idx'), models.Index(fields=['is_featured', 'order'], name='gallery_gal_is_feat_d71399_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tattoo_image__isnull', False), ('artwork_image__isnull', False), _negated=True), name='gallery_image_single_provenance')],
            },
        ),
    ]
