"""
Media storage: local filesystem by default, Supabase Storage when configured.

WHY THIS IS CONDITIONAL
-----------------------
Vercel Functions have a read-only filesystem apart from an ephemeral `/tmp`, so an image
written to `MEDIA_ROOT` during an upload does not survive the request that created it. The
derivatives generated by `ingest_image` would be written, then discarded, leaving database
rows pointing at files that no longer exist. Object storage is therefore required in
production.

Supabase Storage exposes an S3-compatible API, so django-storages' S3 backend is the whole
implementation -- no custom storage class, no new abstraction.

The switch is driven by environment variables rather than by environment *name*, so local
development needs no credentials and no branch on DEBUG. Set the four Supabase variables in
the Vercel project and media moves to object storage; leave them unset and it stays on disk.
"""

from __future__ import annotations

import os

# S3-compatible endpoint for the Supabase project, e.g.
#   https://<project-ref>.supabase.co/storage/v1/s3
SUPABASE_S3_ENDPOINT = os.environ.get("SUPABASE_S3_ENDPOINT", "").strip()

# Credentials from the Supabase dashboard (Project Settings -> Storage -> S3 access keys).
SUPABASE_S3_ACCESS_KEY = os.environ.get("SUPABASE_S3_ACCESS_KEY", "").strip()
SUPABASE_S3_BUCKET = os.environ.get("SUPABASE_S3_BUCKET", "").strip()
# Supabase documents a fixed region for its S3 gateway; required by the SDK but not
# meaningful, since the endpoint above decides where the request actually goes.
SUPABASE_S3_REGION = os.environ.get("SUPABASE_S3_REGION", "us-east-1").strip()

# Public base for reading the bucket back. Supabase serves objects from
#   https://<project-ref>.supabase.co/storage/v1/object/public/<bucket>
# Set SUPABASE_MEDIA_URL to that, or to a custom domain, when using a public bucket.
SUPABASE_MEDIA_URL = os.environ.get("SUPABASE_MEDIA_URL", "").strip()


def supabase_storage_enabled() -> bool:
    """
    True only when enough configuration exists to actually reach Supabase.

    All of endpoint, keys and bucket are required. Checking them together means a
    half-configured deployment falls back to the filesystem rather than failing at the first
    upload with an opaque boto3 error -- and it keeps local development credential-free.
    """
    return all(
        [
            SUPABASE_S3_ENDPOINT,
            SUPABASE_S3_ACCESS_KEY,
            os.environ.get('SUPABASE_S3_SECRET_KEY', "").strip(),
            SUPABASE_S3_BUCKET,
        ]
    )


def media_storage_config() -> dict:
    """The `default` entry for STORAGES, as a dict so callers can splat it in."""
    if not supabase_storage_enabled():
        return {"BACKEND": "django.core.files.storage.FileSystemStorage"}

    # Not using S3Storage's `custom_domain` blindly: it prefixes the bucket name
    # automatically, which would double it up against Supabase's /object/public/<bucket>
    # path, so the value is passed through unchanged.
    custom_domain = SUPABASE_MEDIA_URL or None

    options = {
        "access_key": SUPABASE_S3_ACCESS_KEY,
        "secret_key": os.environ.get('SUPABASE_S3_SECRET_KEY', "").strip(),
        "bucket_name": SUPABASE_S3_BUCKET,
        "endpoint_url": SUPABASE_S3_ENDPOINT,
        "region_name": SUPABASE_S3_REGION,
        # Supabase's S3 gateway is path-style; virtual-host style would address
        # <bucket>.<project>.supabase.co, which does not exist.
        "addressing_style": "path",
        # The bucket is public, so files are served directly without signed URLs. Signed
        # URLs would expire and break already-published artwork pages.
        "querystring_auth": False,
        "file_overwrite": False,
    }
    if custom_domain:
        options["custom_domain"] = custom_domain

    return {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": options,
    }


# Media URLs. With Supabase configured, MEDIA_URL must be absolute or the templates emit
# relative paths that 404 against the Django origin instead of the storage host.
MEDIA_URL_VALUE = (
    SUPABASE_MEDIA_URL.rstrip("/") + "/"
    if SUPABASE_MEDIA_URL
    else "/media/"
)
