# Generated by Django 5.2.17 on 2026-09-24 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.mediaasset')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tattoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=320)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('artist_notes', models.TextField(blank=True, help_text='Shown on the detail page.')),
                ('placement', models.CharField(blank=True, db_index=True, help_text='e.g. "Forearm", "Ribs", "Hand", "Back".', max_length=80)),
                ('size_cm', models.CharField(blank=True, help_text='e.g. "12 x 18 cm".', max_length=40)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_color', models.BooleanField(default=False, help_text='Colour vs black & grey.')),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='tattoos', to='core.tag')),
                ('styles', models.ManyToManyField(blank=True, related_name='tattoos', to='tattoos.tattoostyle')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TattooImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('variant', models.CharField(choices=[('detail', 'Detail'), ('healed', 'Healed'), ('process', 'Process'), ('studio', 'Studio')], default='detail', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tattoo_images', to='core.mediaasset')),
                ('tattoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tattoos.tattoo')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['tattoo', 'order'], name='tattoos_tat_tattoo__9a0865_idx')],
                'constraints': [models.UniqueConstraint(fields=('tattoo', 'order'), name='uniq_tattooimage_order'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('tattoo',), name='uniq_tattoo_primary_image')],
            },
        ),
        migrations.AddIndex(
            model_name='tattoostyle',
            index=models.Index(fields=['is_featured', 'order'], name='tattoos_tat_is_feat_0d6794_idx'),
        ),
        migrations.AddIndex(
            model_name='tattoo',
            index=models.Index(fields=['status', 'is_featured', '-published_at'], name='tattoos_tat_status_4a256d_idx'),
        ),
        migrations.AddIndex(
            model_name='tattoo',
            index=models.Index(fields=['placement'], name='tattoos_tat_placeme_63277a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tattoo',
            constraint=models.CheckConstraint(condition=models.Q(('price_to__isnull', True), ('price_from__isnull', True), ('price_to__gte', models.F('price_from')), _connector='OR'), name='tattoo_price_range_valid'),
        ),
    ]
