# Generated by Django 5.2.17 on 2026-09-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('instagram', models.CharField(blank=True, max_length=80)),
                ('telegram', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True, help_text='Private artist notes.')),
                ('preferences', models.TextField(blank=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='clients', to='core.tag')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'), models.Index(fields=['email'], name='clients_cli_email_56b9fc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('email',), name='uniq_client_email_nonempty')],
            },
        ),
    ]
